# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/configuration-reference/ for more details
# Writer: kd52.kim@samsung.com

version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:20.19.2

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          - v2-dependencies-

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
